parameters:
  "service-dir":
    default: "sdk/xyz-analytics"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}"
    output-file: "{version-status}/{version}/xyzanalytics.json"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
  "@azure-typespec/http-client-csharp-mgmt":
    namespace: "Azure.ResourceManager.XYZAnalytics"
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-xyzanalytics"
    namespace: "azure.mgmt.xyzanalytics"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-xyzanalytics"
    namespace: "com.azure.resourcemanager.xyzanalytics"
    service-name: "XYZAnalytics"
    flavor: azure
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-xyzanalytics"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-xyzanalytics"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/xyzanalytics"
    emitter-output-dir: "{output-dir}/{service-dir}/armxyzanalytics"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armxyzanalytics"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
